import json

scan_dict = {
            '0' :  {'RotationStart' : 0, 'RotationStep' : 0.12,  'NumAngles' : 1500, 'ReturnRotation' : 'No', 'NumDarkFields' : 20, 'DarkFieldMode' : 'Start', 'DarkFieldValue' : 0, 'NumFlatFields' : 20, 'FlatFieldMode' : 'Start', 'FlatFieldAxis' : 'X', 'SampleInX' : 0, 'SampleOutX' : 1, 'SampleInY' : 0, 'SampleOutY' : 1, 'SampleOutAngle' : 90, 'SampleOutAngleEnable' : 'No', 'ExposureTime' : 0.01, 'FlatExposureTime' : 0.01, 'DifferentFlatExposure' : 'Same', 'FileName': 'test'},
            '1' :  {'RotationStart' : 0, 'RotationStep' : 0.12,  'NumAngles' : 1500, 'ReturnRotation' : 'No', 'NumDarkFields' : 20, 'DarkFieldMode' : 'Start', 'DarkFieldValue' : 0, 'NumFlatFields' : 20, 'FlatFieldMode' : 'Start', 'FlatFieldAxis' : 'X', 'SampleInX' : 0, 'SampleOutX' : 1, 'SampleInY' : 0, 'SampleOutY' : 1, 'SampleOutAngle' : 90, 'SampleOutAngleEnable' : 'No', 'ExposureTime' : 0.01, 'FlatExposureTime' : 0.01, 'DifferentFlatExposure' : 'Same', 'FileName': 'test'},
            '2' :  {'RotationStart' : 0, 'RotationStep' : 0.12,  'NumAngles' : 1500, 'ReturnRotation' : 'No', 'NumDarkFields' : 20, 'DarkFieldMode' : 'Start', 'DarkFieldValue' : 0, 'NumFlatFields' : 20, 'FlatFieldMode' : 'Start', 'FlatFieldAxis' : 'X', 'SampleInX' : 0, 'SampleOutX' : 1, 'SampleInY' : 0, 'SampleOutY' : 1, 'SampleOutAngle' : 90, 'SampleOutAngleEnable' : 'No', 'ExposureTime' : 0.01, 'FlatExposureTime' : 0.01, 'DifferentFlatExposure' : 'Same', 'FileName': 'test'},
            '3' :  {'RotationStart' : 0, 'RotationStep' : 0.12,  'NumAngles' : 1500, 'ReturnRotation' : 'No', 'NumDarkFields' : 20, 'DarkFieldMode' : 'Start', 'DarkFieldValue' : 0, 'NumFlatFields' : 20, 'FlatFieldMode' : 'Start', 'FlatFieldAxis' : 'X', 'SampleInX' : 0, 'SampleOutX' : 1, 'SampleInY' : 0, 'SampleOutY' : 1, 'SampleOutAngle' : 90, 'SampleOutAngleEnable' : 'No', 'ExposureTime' : 0.01, 'FlatExposureTime' : 0.01, 'DifferentFlatExposure' : 'Same', 'FileName': 'test'},
            '4' :  {'RotationStart' : 0, 'RotationStep' : 0.12,  'NumAngles' : 1500, 'ReturnRotation' : 'No', 'NumDarkFields' : 20, 'DarkFieldMode' : 'Start', 'DarkFieldValue' : 0, 'NumFlatFields' : 20, 'FlatFieldMode' : 'Start', 'FlatFieldAxis' : 'X', 'SampleInX' : 0, 'SampleOutX' : 1, 'SampleInY' : 0, 'SampleOutY' : 1, 'SampleOutAngle' : 90, 'SampleOutAngleEnable' : 'No', 'ExposureTime' : 0.01, 'FlatExposureTime' : 0.01, 'DifferentFlatExposure' : 'Same', 'FileName': 'test'},
            '5' :  {'RotationStart' : 0, 'RotationStep' : 0.12,  'NumAngles' : 1500, 'ReturnRotation' : 'No', 'NumDarkFields' : 20, 'DarkFieldMode' : 'Start', 'DarkFieldValue' : 0, 'NumFlatFields' : 20, 'FlatFieldMode' : 'Start', 'FlatFieldAxis' : 'X', 'SampleInX' : 0, 'SampleOutX' : 1, 'SampleInY' : 0, 'SampleOutY' : 1, 'SampleOutAngle' : 90, 'SampleOutAngleEnable' : 'No', 'ExposureTime' : 0.01, 'FlatExposureTime' : 0.01, 'DifferentFlatExposure' : 'Same', 'FileName': 'test'},
            '6' :  {'RotationStart' : 0, 'RotationStep' : 0.12,  'NumAngles' : 1500, 'ReturnRotation' : 'No', 'NumDarkFields' : 20, 'DarkFieldMode' : 'Start', 'DarkFieldValue' : 0, 'NumFlatFields' : 20, 'FlatFieldMode' : 'Start', 'FlatFieldAxis' : 'X', 'SampleInX' : 0, 'SampleOutX' : 1, 'SampleInY' : 0, 'SampleOutY' : 1, 'SampleOutAngle' : 90, 'SampleOutAngleEnable' : 'No', 'ExposureTime' : 0.01, 'FlatExposureTime' : 0.01, 'DifferentFlatExposure' : 'Same', 'FileName': 'test'},
            '7' :  {'RotationStart' : 0, 'RotationStep' : 0.12,  'NumAngles' : 1500, 'ReturnRotation' : 'No', 'NumDarkFields' : 20, 'DarkFieldMode' : 'Start', 'DarkFieldValue' : 0, 'NumFlatFields' : 20, 'FlatFieldMode' : 'Start', 'FlatFieldAxis' : 'X', 'SampleInX' : 0, 'SampleOutX' : 1, 'SampleInY' : 0, 'SampleOutY' : 1, 'SampleOutAngle' : 90, 'SampleOutAngleEnable' : 'No', 'ExposureTime' : 0.01, 'FlatExposureTime' : 0.01, 'DifferentFlatExposure' : 'Same', 'FileName': 'test'},
            '8' :  {'RotationStart' : 0, 'RotationStep' : 0.12,  'NumAngles' : 1500, 'ReturnRotation' : 'No', 'NumDarkFields' : 20, 'DarkFieldMode' : 'Start', 'DarkFieldValue' : 0, 'NumFlatFields' : 20, 'FlatFieldMode' : 'Start', 'FlatFieldAxis' : 'X', 'SampleInX' : 0, 'SampleOutX' : 1, 'SampleInY' : 0, 'SampleOutY' : 1, 'SampleOutAngle' : 90, 'SampleOutAngleEnable' : 'No', 'ExposureTime' : 0.01, 'FlatExposureTime' : 0.01, 'DifferentFlatExposure' : 'Same', 'FileName': 'test'},
            '8' :  {'RotationStart' : 0, 'RotationStep' : 0.12,  'NumAngles' : 1500, 'ReturnRotation' : 'No', 'NumDarkFields' : 20, 'DarkFieldMode' : 'Start', 'DarkFieldValue' : 0, 'NumFlatFields' : 20, 'FlatFieldMode' : 'Start', 'FlatFieldAxis' : 'X', 'SampleInX' : 0, 'SampleOutX' : 1, 'SampleInY' : 0, 'SampleOutY' : 1, 'SampleOutAngle' : 90, 'SampleOutAngleEnable' : 'No', 'ExposureTime' : 0.01, 'FlatExposureTime' : 0.01, 'DifferentFlatExposure' : 'Same', 'FileName': 'test'},
            '10' : {'RotationStart' : 0, 'RotationStep' : 0.12,  'NumAngles' : 1500, 'ReturnRotation' : 'No', 'NumDarkFields' : 20, 'DarkFieldMode' : 'Start', 'DarkFieldValue' : 0, 'NumFlatFields' : 20, 'FlatFieldMode' : 'Start', 'FlatFieldAxis' : 'X', 'SampleInX' : 0, 'SampleOutX' : 1, 'SampleInY' : 0, 'SampleOutY' : 1, 'SampleOutAngle' : 90, 'SampleOutAngleEnable' : 'No', 'ExposureTime' : 0.01, 'FlatExposureTime' : 0.01, 'DifferentFlatExposure' : 'Same', 'FileName': 'test'},
            }

with open('data.json', 'w') as fp:
    json.dump(scan_dict, fp, indent=4, sort_keys=True)

with open('data.json') as json_file:
    data = json.load(json_file)


if scan_dict == data:
    print("Same")
else:
    print("Different")